version: '3.8'

services:
  redis:
    image: 'redis:7.2.5-alpine'
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - cache:/data
volumes:
  cache:
  # node:
  #   build: ./
  #   container_name: backend-sico
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /Users/macbookpro/Juris/:/app/